const victims = [
  {
      name: "David McAtee",
      dates: "August 3, 1966 - June 1, 2020",
      location: "Louisville, Kentucky", 
      description: "Shot: June 1, 2020, Louisville Metropolitan Police Officer", 
  },
  {
      name: "George Perry Floyd",
      dates: "October 14, 1973 - May 25, 2020",
      location: "Powderhorn, Minneapolis, Minnesota", 
      description: "Knee on neck/Asphyxiated: May 25, 2020, Minneapolis Police Officer", 
  },
  {
      name: "Dreasjon “Sean” Reed",
      dates: "June 16, 1999 - May 6, 2020",
      location: "Indianapolis, Indiana", 
      description: "Shot: May 6, 2020, Unidentified Indianapolis Metropolitan Police Officer", 
  },
  {
      name: "Michael Brent Charles Ramos",
      dates: "January 1, 1978 - April 24, 2020",
      location: "Austin, Texas", 
      description: "Shot: April 24, 2020, Austin Police Detectives", 
  },
  {
      name: "Breonna Taylor",
      dates: "June 5, 1993 - March 13, 2020",
      location: "Louisville, Kentucky", 
      description: "Shot: March 13, 2020, Louisville Metro Police Officers", 
  },
  {
      name: "Manuel “Mannie” Elijah Ellis",
      dates: "August 28, 1986 - March 3, 2020",
      location: "Tacoma, Washington", 
      description: "Physical restraint/Hypoxia: March 3, 2020, Tacoma Police Officers", 
  },
  {
      name: "Atatiana Koquice Jefferson",
      dates: "November 28, 1990 - October 12, 2019",
      location: "Fort Worth, Texas", 
      description: "Shot: October 12, 2019, Fort Worth Police Officer", 
  },
  {
      name: "Emantic “EJ” Fitzgerald Bradford Jr.",
      dates: "June 18, 1997 - November 22, 2018",
      location: "Hoover, Alabama", 
      description: "Shot: November 22, 2018, Unidentified Hoover Police Officers", 
  },
  {
      name: "Charles “Chop” Roundtree Jr.",
      dates: "September 5, 2000 - October 17, 2018",
      location: "San Antonio, Texas", 
      description: "Shot: October 17, 2018, San Antonio Police Officer", 
  },
  {
      name: "Chinedu Okobi",
      dates: "February 13, 1982 - October 3, 2018",
      location: "Millbrae, California", 
      description: "Tasered/Electrocuted: October 3, 2018, San Mateo County Sheriff &nbsp;Sergeant and Sheriff Deputies", 
  },
  {
      name: "Botham Shem Jean",
      dates: "September 29, 1991 - September 6, 2018",
      location: "Dallas, Texas", 
      description: "Shot: September 6, 2018, Dallas Police Officer", 
  },
  {
      name: "Antwon Rose Jr.",
      dates: "July 12, 2000 - June 19, 2018",
      location: "East Pittsburgh, Pennsylvania", 
      description: "Shot: June 19, 2018, East Pittsburgh Police Officer", 
  },
  {
      name: "Saheed Vassell",
      dates: "December 22, 1983 - April 4, 2018",
      location: "Brooklyn, New York City, New York", 
      description: "Shot: April 4, 2018, Four Unnamed New York City Police Officers", 
  },
  {
      name: "Stephon Alonzo Clark",
      dates: "August 10, 1995 - March 18, 2018",
      location: "Sacramento, California", 
      description: "Shot: March 18, 2018, Sacramento Police Officers", 
  },
  {
      name: "Aaron Bailey, 1972 - June 29, 2017",
      location: "Indianapolis, Indiana", 
      description: "Shot: June 29, 2017, Indianapolis Metropolitan Police Officers", 
  },
  {
      name: "Charleena Chavon Lyles",
      dates: "April 24, 1987 - June 18, 2017",
      location: "Seattle, Washington", 
      description: "Shot: June 18, 2017, Seattle Police Officers", 
  },
  {
      name: "Fetus of Charleena Chavon Lyles (14-15 weeks)",
      dates: "June 18, 2017",
      location: "Seattle, Washington", 
      description: "Shot: June 18, 2017, Seattle Police Officers", 
  },
  {
      name: "Jordan Edwards",
      dates: "October 25, 2001 - April 29, 2017",
      location: "Balch Springs, Texas", 
      description: "Shot: April 29, 2017, Balch Springs Officer", 
  },
  {
      name: "Chad Robertson, 1992 - February 15, 2017",
      location: "Chicago, Illinois", 
      description: "Shot: February 8, 2017, Chicago Police Officer", 
  },
  {
      name: "Deborah Danner",
      dates: "September 25, 1950 - October 18, 2016",
      location: "The Bronx, New York City, New York", 
      description: "Shot: October 18, 2016, New York City Police Officers", 
  },
  {
      name: "Alfred Olango",
      dates: "July 29, 1978 - September 27, 2016",
      location: "El Cajon, California", 
      description: "Shot: September 27, 2016, El Cajon Police Officers", 
  },
  {
      name: "Terence Crutcher",
      dates: "August 16, 1976 - September 16, 2016",
      location: "Tulsa, Oklahoma", 
      description: "Shot: September 16, 2016, Tulsa Police Officer", 
  },
  {
      name: "Terrence LeDell Sterling",
      dates: "July 31, 1985 - September 11, 2016",
      location: "Washington, DC", 
      description: "Shot: September 11, 2016, Washington Metropolitan Police Officer", 
  },
  {
      name: "Korryn Gaines",
      dates: "August 24, 1993 - August 1, 2016",
      location: "Randallstown, Maryland", 
      description: "Shot: August 1, 2016, Baltimore County Police", 
  },
  {
      name: "Joseph Curtis Mann, 1966 - July 11, 2016",
      location: "Sacramento, California", 
      description: "Shot: July 11, 2016, Sacramento Police Officers", 
  },
  {
      name: "Philando Castile",
      dates: "July 16, 1983 - July 6, 2016",
      location: "Falcon Heights, Minnesota", 
      description: "Shot: July 6, 2016, St. Anthony Police Officer", 
  },
  {
      name: "Alton Sterling",
      dates: "June 14, 1979 - July 5, 2016",
      location: "Baton Rouge, Louisiana", 
      description: "Shot: July 5, 2016, Baton Rouge Police Officers", 
  },
  {
      name: "Bettie “Betty Boo” Jones, 1960 - December 26, 2015",
      location: "Chicago, Illinois", 
      description: "Shot: December 26, 2015, Chicago Police Officer", 
  },
  {
      name: "Quintonio LeGrier",
      dates: "April 29, 1996 - December 26, 2015",
      location: "Chicago, Illinois", 
      description: "Shot: December 26, 2015, Chicago Police Officer", 
  },
  {
      name: "Corey Lamar Jones",
      dates: "February 3, 1984 - October 18, 2015",
      location: "Palm Beach Gardens, Florida", 
      description: "Shot: October 18, 2015, Palm Beach Gardens Police Officer", 
  },
  {
      name: "Jamar O’Neal Clark",
      dates: "May 3, 1991 - November 16, 2015",
      location: "Minneapolis, Minnesota", 
      description: "Shot: November 15, 2015, Minneapolis Police Officers", 
  },
  {
      name: "Jeremy “Bam Bam” McDole, 1987 - September 23, 2015",
      location: "Wilmington, Delaware", 
      description: "Shot: September 23, 2015, Wilmington Police Officers", 
  },
  {
      name: "India Kager",
      dates: "June 9, 1988 - September 5, 2015",
      location: "Virginia Beach, Virginia", 
      description: "Shot: September 5, 2015, Virginia Beach Police Officers", 
  },
  {
      name: "Samuel Vincent DuBose",
      dates: "March 12, 1972 - July 19, 2015",
      location: "Cincinnati, Ohio", 
      description: "Shot: July 19, 2015, University of Cincinnati Police Officer", 
  },
  {
      name: "Sandra Bland",
      dates: "February 7, 1987 - July 13, 2015",
      location: "Waller County, Texas", 
      description: "Excessive Force/Wrongful Death/Suicide (?): July 10, 2015, Texas State Trooper", 
  },
  {
      name: "Brendon K. Glenn, 1986 - May 5, 2015",
      location: "Venice, California", 
      description: "Shot: May 5, 2015, Los Angeles Police Officer", 
  },
  {
      name: "Freddie Carlos Gray Jr.",
      dates: "August 16, 1989 - April 19, 2015",
      location: "Baltimore, Maryland", 
      description: "Brute Force/Spinal Injuries: April 12, 2015, Baltimore City Police Officers", 
  },
  {
      name: "Walter Lamar Scott",
      dates: "February 9, 1965 - April 4, 2015",
      location: "North Charleston, South Carolina", 
      description: "Shot: April 4, 2015, North Charleston Police Officer", 
  },
  {
      name: "Eric Courtney Harris",
      dates: "October 10, 1971 - April 2, 2015",
      location: "Tulsa, Oklahoma", 
      description: "Shot: April 2, 2015, Tulsa County Reserve Deputy", 
  },
  {
      name: "Phillip Gregory White, 1982 - March 31, 2015",
      location: "Vineland, New Jersey", 
      description: "K-9 Mauling/Respiratory distress: March 31, 2015, Vineland Police Officers", 
  },
  {
      name: "Mya Shawatza Hall",
      dates: "December 5, 1987 - March 30, 2015",
      location: "Fort Meade, Maryland", 
      description: "Shot: March 30, 2015, National Security Agency Police Officers", 
  },
  {
      name: "Meagan Hockaday",
      dates: "August 27, 1988 - March 28, 2015",
      location: "Oxnard, California", 
      description: "Shot: March 28, 2015, Oxnard Police Officer", 
  },
  {
      name: "Tony Terrell Robinson, Jr.",
      dates: "October 18, 1995 - March 6, 2015",
      location: "Madison, Wisconsin", 
      description: "Shot: March 6, 2015, Madison Police Officer", 
  },
  {
      name: "Janisha Fonville",
      dates: "March 3, 1994 - February 18 2015",
      location: "Charlotte, North Carolina", 
      description: "Shot: February 18, 2015, Charlotte-Mecklenburg Police Officer", 
  },
  {
      name: "Natasha McKenna",
      dates: "January 9, 1978 - February 8, 2015",
      location: "Fairfax County, Virginia", 
      description: "Tasered/Cardiac Arrest: February 3, 2015, Fairfax County Sheriff Deputies", 
  },
  {
      name: "Jerame C. Reid",
      dates: "June 8, 1978 - December 30, 2014",
      location: "Bridgeton, New Jersey", 
      description: "Shot: December 30, 2014, Bridgeton Police Officer", 
  },
  {
      name: "Rumain Brisbon",
      dates: "November 24, 1980 - December 2, 2014",
      location: "Phoenix, Arizona", 
      description: "Shot: December 2, 2014,  Phoenix Police Officer", 
  },
  {
      name: "Tamir Rice",
      dates: "June 15, 2002 - November 22, 2014",
      location: "Cleveland, Ohio", 
      description: "Shot: November 22, 2014, Cleveland Police Officer", 
  },
  {
      name: "Akai Kareem Gurley",
      dates: "November 12, 1986 - November 20, 2014",
      location: "Brooklyn, New York City, New York", 
      description: "Shot: November 20, 2014, New York City Police Officer", 
  },
  {
      name: "Tanisha N. Anderson",
      dates: "January 22, 1977 - November 13, 2014",
      location: "Cleveland, Ohio", 
      description: "Physically Restrained/Brute Force: November 13, 2014, Cleveland Police Officers", 
  },
  {
      name: "Dante Parker",
      dates: "August 14, 1977 - August 12, 2014",
      location: "Victorville, California", 
      description: "Tasered/Excessive Force: August 12, 2014, San Bernardino County Sheriff Deputies", 
  },
  {
      name: "Ezell Ford",
      dates: "October 14, 1988 - August 11, 2014",
      location: "Florence, Los Angeles, California", 
      description: "Shot: August 11, 2014, Los Angeles Police Officers", 
  },
  {
      name: "Michael Brown Jr.",
      dates: "May 20, 1996 - August 9, 2014",
      location: "Ferguson, Missouri", 
      description: "Shot: August 9, 2014, Ferguson Police Officer", 
  },
  {
      name: "John Crawford III",
      dates: "July 29, 1992 - August 5, 2014",
      location: "Beavercreek, Ohio", 
      description: "Shot: August 5, 2014, Beavercreek Police Officer", 
  },
  {
      name: "Eric Garner",
      dates: "September 15, 1970 - July 17, 2014",
      location: "Staten Island, New York", 
      description: "Choke hold/Suffocated: July 17, 2014, New York City Police Officer", 
  },
  {
      name: "Dontre Hamilton",
      dates: "January 20, 1983 - April 30, 2014",
      location: "Milwaukee, Wisconsin", 
      description: "Shot: April 30, 2014, Milwaukee Police Officer", 
  },
  {
      name: "Victor White III",
      dates: "September 11, 1991 - March 3, 2014",
      location: "New Iberia, Louisiana", 
      description: "Shot: March 2, 2014, Iberia Parish Sheriff Deputy", 
  },
  {
      name: "Gabriella Monique Nevarez",
      dates: "November 25, 1991 - March 2, 2014",
      location: "Citrus Heights, California", 
      description: "Shot: March 2, 2014, Citrus Heights Police Officers", 
  },
  {
      name: "Yvette Smith",
      dates: "December 18, 1966 - February 16, 2014",
      location: "Bastrop County, Texas", 
      description: "Shot: February 16, 2014, Bastrop County Sheriff Deputy", 
  },
  {
      name: "McKenzie J. Cochran",
      dates: "August 25, 1988 - January 29, 2014",
      location: "Southfield, Michigan", 
      description: "Pepper Sprayed/Compression Asphyxiation: January 28, 2014, Northland Mall Security Guards", 
  },
  {
      name: "Jordan Baker, 1988 - January 16, 2014",
      location: "Houston, Texas", 
      description: "Shot: January 16, 2014, Off-duty Houston Police Officer", 
  },
  {
      name: "Andy Lopez",
      dates: "June 2, 2000 - October 22, 2013",
      location: "Santa Rosa, California", 
      description: "Shot: October 22, 2013, Sonoma County Sheriff Deputy", 
  },
  {
      name: "Miriam Iris Carey",
      dates: "August 12, 1979 - October 3, 2013",
      location: "Washington, DC", 
      description: "Shot 26 times: October 3, 2013, U. S. Secret Service Officer", 
  },
  {
      name: "Barrington “BJ” Williams, 1988 - September 17, 2013",
      location: "New York City, New York", 
      description: "Neglect/Disdain/Asthma Attack: September 17, 2013, New York City Police Officers", 
  },
  {
      name: "Jonathan Ferrell",
      dates: "October 11, 1989 - September 14, 2013",
      location: "Charlotte, North Carolina", 
      description: "Shot: September 14, 2013, Charlotte-Mecklenburg  Police Officer", 
  },
  {
      name: "Carlos Alcis, 1970 - August 15, 2013",
      location: "Brooklyn, New York City", 
      description: "Heart Attack/Neglect: August 15, 2013, New York City Police Officers", 
  },
  {
      name: "Larry Eugene Jackson Jr.",
      dates: "November 29, 1980 - July 26, 2013",
      location: "Austin, Texas", 
      description: "Shot: July 26, 2013, Austin Police Detective", 
  },
  {
      name: "Kyam Livingston",
      dates: "July 29, 1975 - July 21, 2013",
      location: "New York City, New York", 
      description: "Neglect/Ignored pleas for help: July 20-21, 2013, New York City Police Officers", 
  },
  {
      name: "Clinton R. Allen",
      dates: "September 26, 1987 - March 10, 2013",
      location: "Dallas, Texas", 
      description: "Tasered and Shot: March 10, 2013, Dallas Police Officer", 
  },
  {
      name: "Kimani “KiKi” Gray",
      dates: "October 19, 1996 - March 9, 2013",
      location: "Brooklyn, New York City, New York", 
      description: "Shot: March 9, 2013, New York Police Officers", 
  },
  {
      name: "Kayla Moore",
      dates: "April 17, 1971 - February 13, 2013",
      location: "Berkeley, California", 
      description: "Restrained face-down prone: February 12, 2013, Berkeley Police Officers", 
  },
  {
      name: "Jamaal Moore Sr., 1989 - December 15, 2012",
      location: "Chicago, Illinois", 
      description: "Shot: December 15, 2012, Chicago Police Officer", 
  },
  {
      name: "Johnnie Kamahi Warren",
      dates: "February 26, 1968 - February 13, 2012",
      location: "Dothan, Alabama", 
      description: "Tasered/Electrocuted: December 10, 2012, Houston County (AL) Sheriff Deputy", 
  },
  {
      name: "Shelly Marie Frey",
      dates: "April 21, 1985 - December 6, 2012",
      location: "Houston, Texas", 
      description: "Shot: December 6, 2012, Off-duty Harris County Sheriff's Deputy", 
  },
  {
      name: "Darnisha Diana Harris",
      dates: "December 11, 1996 - December 2, 2012",
      location: "Breaux Bridge, Louisiana", 
      description: "Shot: December 2, 2012, Breaux Bridge Police Office", 
  },
  {
      name: "Timothy Russell",
      dates: "December 9. 1968 - November 29, 2012",
      location: "Cleveland, Ohio", 
      description: "137 Rounds/Shot 23 times: November 29, 2012, Cleveland Police Officers", 
  },
  {
      name: "Malissa Williams",
      dates: "June 20, 1982 - November 29, 2012",
      location: "Cleveland, Ohio", 
      description: "137 Rounds/Shot 24 times: November 29, 2012, Cleveland Police Officers", 
  },
  {
      name: "Noel Palanco",
      dates: "November 28, 1989 - October 4, 2012",
      location: "Queens, New York City, New York", 
      description: "Shot: October 4, 2012, New York City Police Officers", 
  },
  {
      name: "Reynaldo Cuevas",
      dates: "January 6, 1992 - September 7, 2012",
      location: "Bronx, New York City, New York", 
      description: "Shot: September 7, 2012, New York City Police Officer", 
  },
  {
      name: "Chavis Carter, 1991 - July 28, 2012",
      location: "Jonesboro, Arkansas", 
      description: "Shot: July 28, 2012, Jonesboro Police Officer", 
  },
  {
      name: "Alesia Thomas",
      dates: "June 1, 1977 - July 22, 2012",
      location: "Los Angeles, California", 
      description: "Brutal Force/Beaten: July 22, 2012, Los Angeles Police Officers", 
  },
  {
      name: "Shantel Davis",
      dates: "May 26, 1989 - June 14, 2012",
      location: "New York City, New York", 
      description: "Shot: June 14, 2012, New York City Police Officer", 
  },
  {
      name: "Sharmel T. Edwards",
      dates: "October 10, 1962 - April 21, 2012",
      location: "Las Vegas, Nevada", 
      description: "Shot: April 21, 2012, Las Vegas Police Officers", 
  },
  {
      name: "Tamon Robinson",
      dates: "December 21, 1985 - April 18, 2012",
      location: "Brooklyn, New York City, New York", 
      description: "Run over by police car: April 12, 2012, New York City Police Officers", 
  },
  {
      name: "Ervin Lee Jefferson, III, 1994 - March 24, 2012",
      location: "Atlanta, Georgia", 
      description: "Shot: March 24, 2012, Shepperson Security &amp;Escort Services Security Guards", 
  },
  {
      name: "Kendrec McDade",
      dates: "May 5, 1992 - March 24, 2012",
      location: "Pasadena, California", 
      description: "Shot: March 24, 2012, Pasadena Police Officers", 
  },
  {
      name: "Rekia Boyd",
      dates: "November 5, 1989 - March 21, 2012",
      location: "Chicago, Illinois", 
      description: "Shot: March 21, 2012, Off-duty Chicago Police Detective", 
  },
  {
      name: "Shereese Francis, 1982 - March 15, 2012",
      location: "Queens, New York City, New York", 
      description: "Suffocated to death: March 15, 2012,  New York City Police Officers", 
  },
  {
      name: "Jersey K. Green",
      dates: "June 17, 1974 - March 12, 2012",
      location: "Aurora, Illinois", 
      description: "Tasered/Electrocuted: March 12, 2012, Aurora Police Officers", 
  },
  {
      name: "Wendell James Allen",
      dates: "December 19, 1991 - March 7, 2012",
      location: "New Orleans, Louisiana", 
      description: "Shot:  March 7, 2012, New Orleans Police Officer", 
  },
  {
      name: "Nehemiah Lazar Dillard",
      dates: "July 29, 1982 - March 5, 2012",
      location: "Gainesville, Florida", 
      description: "Tasered/Electrocuted: March 5, 2012, Alachua County Sheriff Deputies", 
  },
  {
      name: "Dante’ Lamar Price",
      dates: "July 18, 1986 - March 1, 2012",
      location: "Dayton, Ohio", 
      description: "Shot: March 1, 2012, Ranger Security Guards", 
  },
  {
      name: "Raymond Luther Allen Jr., 1978 - February 29, 2012",
      location: "Galveston, Texas", 
      description: "Tasered/Electrocuted: February 27, 2012, Galveston Police Officers", 
  },
  {
      name: "Manual Levi Loggins Jr.",
      dates: "February 22, 1980 - February 7, 2012",
      location: "San Clemente, Orange County, California", 
      description: "Shot: February 7, 2012, Orange County Sheriff Deputy", 
  },
  {
      name: "Ramarley Graham",
      dates: "April 12, 1993 - February 2, 2012",
      location: "The Bronx, New York City, New York", 
      description: "Shot: February 2, 2012, New York City Police Officer", 
  },
  {
      name: "Kenneth Chamberlain Sr.",
      dates: "April 12, 1943 - November 19, 2011",
      location: "White Plains, New York", 
      description: "Tasered/Electrocuted/Shot: November 19, 2011, White Plains Police Officers", 
  },
  {
      name: "Alonzo Ashley",
      dates: "June 10, 1982 - July 18, 2011",
      location: "Denver, Colorado", 
      description: "Tasered/Electrocuted: July 18, 2011, Denver Police Officers", 
  },
  {
      name: "Derek Williams",
      dates: "January 23, 1989 - July 6, 2011",
      location: "Milwaukee, Wisconsin", 
      description: "Blunt Force/Respiratory distress: July 6, 2011, Milwaukee Police Officers", 
  },
  {
      name: "Raheim Brown, Jr.",
      dates: "March 4, 1990 - January 22, 2011",
      location: "Oakland, California", 
      description: "Shot: January 22, 2011, Oakland Unified School District Police", 
  },
  {
      name: "Reginald Doucet",
      dates: "June 3, 1985 - January 14, 2011",
      location: "Los Angeles, California", 
      description: "Shot: January 14, 2011, Los Angeles Police Officer", 
  },
  {
      name: "Derrick Jones",
      dates: "September 30, 1973 - November 8, 2010",
      location: "Oakland, California", 
      description: "Shot: November 8, 2010, Oakland Police Officers", 
  },
  {
      name: "Danroy “DJ” Henry Jr.",
      dates: "October 29, 1990 - October 17, 2010",
      location: "Pleasantville, New York", 
      description: "Shot: October 17, 2020, Pleasantville Police Officer", 
  },
  {
      name: "Aiyana Mo'Nay Stanley-Jones",
      dates: "July 20, 2002 - May 16, 2010",
      location: "Detroit, Michigan", 
      description: "Shot: May 16, 2010, Detroit Police Officer", 
  },
  {
      name: "Steven Eugene Washington",
      dates: "September 20, 1982 - March 20, 2010",
      location: "Los Angeles, California", 
      description: "Shot: March 20, 2010, Los Angeles County Police", 
  },
  {
      name: "Aaron Campbell",
      dates: "September 7, 1984 - January 29, 2010",
      location: "Portland, Oregon", 
      description: "Shot: January 29, 2010, Portland Police Officer", 
  },
  {
      name: "Kiwane Carrington",
      dates: "July 14, 1994 - October 9, 2009",
      location: "Champaign, Illinois", 
      description: "Shot: October 9, 2019, Champaign Police Officer", 
  },
  {
      name: "Victor Steen",
      dates: "November 11, 1991 - October 3, 2009",
      location: "Pensacola, Florida", 
      description: "Tasered/Run over: October 3, 2009, Pensacola Police Officer", 
  },
  {
      name: "Shem Walker,  March 18, 1960 - July 11, 2009",
      location: "Brooklyn, New York", 
      description: "Shot: July 11, 2009, New York City Undercover C-94 Police Officer", 
  },
  {
      name: "Oscar Grant III",
      dates: "February 27, 1986 - January 1, 2009",
      location: "Oakland, California", 
      description: "Shot: January 1, 2009, BART Police Officer", 
  },
  {
      name: "Tarika Wilson",
      dates: "October 30, 1981 - January 4, 2008",
      location: "Lima, Ohio", 
      description: "Shot January 4, 2008, Lima Police Officer", 
  },
  {
      name: "DeAunta Terrel Farrow",
      dates: "September 7, 1994 - June 22, 2007",
      location: "West Memphis, Arkansas", 
      description: "Shot: June 22, 2007, West Memphis (AR) Police Officer", 
  },
  {
      name: "Sean Bell",
      dates: "May 23, 1983 - November 25, 2006",
      location: "Queens, New York City, New York", 
      description: "Shot: November 25, 2006, New York City Police Officers", 
  },
  {
      name: "Kathryn Johnston",
      dates: "June 26, 1914 - November 21, 2006",
      location: "Atlanta, Georgia", 
      description: "Shot: November 21, 2006, Undercover Atlanta Police Officers", 
  },
  {
      name: "Ronald Curtis Madison",
      dates: "March 1, 1965 - September 4, 2005",
      location: "Danziger Bridge, New Orleans, Louisiana", 
      description: "Shot: September 4, 2005, New Orleans Police Officers", 
  },
  {
      name: "James B. Brissette Jr.",
      dates: "November 6, 1987 - September 4, 2005",
      location: "Danziger Bridge, New Orleans, Louisiana", 
      description: "Shot: September 4, 2005, New Orleans Police Officers", 
  },
  {
      name: "Henry “Ace” Glover",
      dates: "October 2, 1973 - September 2, 2005",
      location: "New Orleans, Louisiana", 
      description: "Shot: September 2, 2005, New Orleans Police Officers", 
  },
  {
      name: "Timothy Stansbury, Jr.",
      dates: "November 16, 1984 - January 24, 2004",
      location: "Brooklyn, New York City, New York", 
      description: "Shot: January 24, 2004, New York City Police Officer", 
  },
  {
      name: "Ousmane Zongo, 1960 - May 22, 2003",
      location: "New York City, New York", 
      description: "Shot: May 22, 2003, New York City Police Officer", 
  },
  {
      name: "Alberta Spruill, 1946 - May 16, 2003",
      location: "New York City, New York", 
      description: "Stun grenade thrown into her apartment led to a heart attack: May 16, 2003, New York City Police Officer", 
  },
  {
      name: "Kendra Sarie James",
      dates: "December 24, 1981 - May 5, 2003",
      location: "Portland, Oregon", 
      description: "Shot: May 5, 2003, Portland Police Officer", 
  },
  {
      name: "Orlando Barlow",
      dates: "December 29, 1974 - February 28, 2003",
      location: "Las Vegas, Nevada", 
      description: "Shot: February 28, 2003, Las Vegas Police Officer", 
  },
  {
      name: "Timothy DeWayne Thomas Jr.",
      dates: "July 25, 1981 - April 7, 2001",
      location: "Cincinnati, Ohio", 
      description: "Shot: April 7, 2001, Cincinnati Police Patrolman", 
  },
  {
      name: "Ronald Beasley, 1964 - June 12, 2000",
      location: "Dellwood, Missouri", 
      description: "Shot: June 12, 2000, Dellwood Police Officers", 
  },
  {
      name: "Earl Murray, 1964 - June 12, 2000",
      location: "Dellwood, Missouri", 
      description: "Shot: June 12, 2000, Dellwood Police Officers", 
  },
  {
      name: "Patrick Moses Dorismond",
      dates: "February 28, 1974 - March 16, 2000",
      location: "New York City, New York", 
      description: "Shot: March 16, 2000, New York City Police Officer", 
  },
  {
      name: "Prince Carmen Jones Jr.",
      dates: "March 30, 1975 - September 1, 2000",
      location: "Fairfax County, Virginia", 
      description: "Shot: September 1, 2000, Prince George’s County Police Officer", 
  },
  {
      name: "Malcolm Ferguson",
      dates: "October 31, 1976 - March 1, 2000",
      location: "The Bronx, New York City, New York", 
      description: "Shot: March 1, 2000, New York City Police Officer", 
  },
  {
      name: "LaTanya Haggerty, 1973 - June 4, 1999",
      location: "Chicago, Illinois", 
      description: "Shot: June 4, 1999, Chicago Police Officer", 
  },
  {
      name: "Margaret LaVerne Mitchell, 1945 - May 21, 1999",
      location: "Los Angeles, California", 
      description: "Shot: May 21, 1999, Los Angeles Police Officer", 
  },
  {
      name: "Amadou Diallo",
      dates: "September 2, 1975 - February 4, 1999",
      location: "The Bronx, New York City, New York", 
      description: "Shot: February 4, 1999, New York City Police Officers", 
  },
  {
      name: "Tyisha Shenee Miller",
      dates: "March 9, 1979 - December 28, 1998",
      location: "Riverside, California", 
      description: "Shot: December 28, 1998, Riverside Police Officers", 
  },
  {
      name: "Dannette Daniels",
      dates: "January 25, 1966 - June 7, 1997",
      location: "Newark, New Jersey", 
      description: "Shot: June 7, 1997, Newark Police Officer", 
  },
  {
      name: "Frankie Ann Perkins, 1960 - March 22, 1997",
      location: "Chicago, Illinois", 
      description: "Brutal Force/Strangled: March 22, 1997, Chicago Police Officers", 
  },
  {
      name: "Nicholas Heyward Jr.",
      dates: "August 26, 1981 - September 27, 1994",
      location: "Brooklyn, New York City, New York", 
      description: "Shot: September 27, 1994, New York City Police Officer", 
  },
  {
      name: "Mary Mitchell, 1950 - November 3, 1991",
      location: "The Bronx, New York City, New York", 
      description: "Shot: November 3, 1991, New York City Police Officer", 
  },
  {
      name: "Yvonne Smallwood, 1959 - December 9, 1987",
      location: "New York City, New York", 
      description: "Severely beaten/Massive blood clot: December 3, New York City Police Officers", 
  },
  {
      name: "Eleanor Bumpers",
      dates: "August 22, 1918 - October 29, 1984",
      location: "The Bronx, New York City, New York", 
      description: "Shot: October 29, 1984, New York City Police Officer", 
  },
  {
      name: "Michael Jerome Stewart",
      dates: "May 9, 1958 - September 28, 1983",
      location: "New York City, New York", 
      description: "Brutal Force: September 15, 1983, New York City Transit Police", 
  },
  {
      name: "Eula Mae Love",
      dates: "August 8, 1939 - January 3, 1979",
      location: "Los Angeles, California", 
      description: "Shot: January 3, 1979, Los Angeles County Police Officers", 
  },
  {
      name: "Arthur Miller Jr., 1943 - June 14, 1978",
      location: "Brooklyn, New York City, New York", 
      description: "Chokehold/Strangled: June 14, 1978, New York City Police Officers", 
  },
  {
      name: "Randolph Evans",
      dates: "April 5, 1961 - November 25, 1976",
      location: "Brooklyn, New York City, New York", 
      description: "Shot in head: November 25, 1976, New York City Police Officer", 
  },
  {
      name: "Barry Gene Evans",
      dates: "August 29, 1958 - February 10, 1976",
      location: "Los Angeles, California", 
      description: "Shot: February 10, 1976, Los Angeles Police Officers", 
  },
  {
      name: "Rita Lloyd",
      dates: "January 27, 1973",
      location: "New York City, New York", 
      description: "Shot: January 27, 1973, New York City Police Officer", 
  },
  {
      name: "Henry Dumas",
      dates: "July 20, 1934 - May 23, 1968",
      location: "Harlem, New York City, New York", 
      description: "Shot: May 23, 1968, New York City Transit Police Officer", 
  }

];